# Site settings
title: Joseph Wang
email: egpivo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Science is a means whereby learning is achieved.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  egpivo

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}
timezone: Asia/Taipei
encoding: "utf-8"
exclude:
  - "*.Rmd"
  - "_site"
  - "node_modules"
  - "vendor"
  - "tmp"
  - "coverage"
  - "lcov.info"
  - "payg-service-contracts"
  - "qa-hub"
  - "tmp_repo"
  - cache
  - README.md
  - package-lock.json
  - package.json
  - Gemfile
  - Gemfile.lock
  # 开发时可以临时排除大的 assets 目录以加速构建
  # - "assets/books"
# Google services
google_analytics: UA-16805442-1

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Sass settings
sass:
  quiet_deps: true
